#!/bin/bash

#Create Variable for storing the current date (mm-dd-yy)
today=$(date +'%m-%d-%y')
source=<SOURCE BUCKET NAME>
destination=<DESTINATION BUCKET NAME>
cldfnt=$(aws cloudfront list-distributions --query "DistributionList.Items[].{Id: Id, OriginDomainName: Origins.Items[0].DomainName}[?contains(OriginDomainName, '$destination')] | [0].Id" | sed 's/.$//; s/^.//')

# Backup Destination files to a backup bucket in the event of needing to rollback changes
aws s3 sync s3://$destination/ s3://Backup_Bucket/${destination}/${today}/

# Sync all files from Source to Destination bucket
aws s3 sync --delete s3://$source s3://$destination

# List all new files in Production bucket
aws s3 ls $destination

# Invalidate Cloudfront files for corresponding URL
aws cloudfront create-invalidation --distribution-id $cldfnt --paths "/*"
